import AppKit
import CryptoKit
import Foundation
import Security

/// Stands in for the system clipboard in tests: what it holds, how often its data was read, what was written back.
final class FakePasteboard: ClipPasteboard {
    var changeCount = 0
    var content = ClipSnapshot()
    var dataReads = 0
    var emptyReadsLeft = 0          // content declared but not there yet, for this many reads
    var written: [ClipItem] = []

    func put(_ s: ClipSnapshot) { changeCount += 1; content = s }

    func snapshot(maxImageBytes: Int, allowed: ([String], String?) -> Bool) -> ClipSnapshot {
        var s = ClipSnapshot(changeCount: changeCount, types: content.types, source: content.source, ours: content.ours)
        guard !s.ours, allowed(s.types, s.source) else { return s }
        if emptyReadsLeft > 0 { emptyReadsLeft -= 1; return s }
        dataReads += 1
        s.text = content.text; s.files = content.files; s.image = content.image
        s.width = content.width; s.height = content.height
        if let i = s.image, i.count > maxImageBytes { s.image = nil; s.imageTooBig = true }
        return s
    }

    func write(_ item: ClipItem, payload: Data?) -> Int? {
        if item.kind == .files && !item.paths.contains(where: { FileManager.default.fileExists(atPath: $0) }) { return nil }
        if item.kind == .image && payload == nil { return nil }
        changeCount += 1
        content = ClipSnapshot(types: [ClipRules.ownType], ours: true, text: item.kind == .text ? item.text : nil)
        written.append(item)
        return changeCount
    }
}

enum ClipboardTests {
    /// Runs every clipboard check (temporary folders, a fake Keychain, a fake or uniquely named pasteboard: never the user's
    /// clipboard, files or Keychain). Prints PASS/FAIL lines; returns the number of failures.
    static func run() -> Int {
        var failed = 0
        func check(_ name: String, _ ok: Bool) { print((ok ? "PASS" : "FAIL") + "  clipboard: " + name); if !ok { failed += 1 } }
        let fm = FileManager.default
        let root = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("cocaine-clip-\(getpid())-\(UUID().uuidString.prefix(6))")
        try? fm.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: root) }
        func defaults() -> UserDefaults { MemoryDefaults() }
        func text(_ t: String, types: [String] = ["public.utf8-plain-text"], source: String? = nil) -> ClipSnapshot {
            ClipSnapshot(types: types, source: source, text: t)
        }
        let base = ClipSettings()

        // MARK: what is never kept
        func kept(_ s: ClipSnapshot, _ settings: ClipSettings = ClipSettings()) -> Bool {
            if case .keep = ClipRules.decide(s, settings: settings) { return true } else { return false }
        }
        func skip(_ s: ClipSnapshot, _ settings: ClipSettings = ClipSettings()) -> ClipRules.Skip? {
            if case .skip(let r) = ClipRules.decide(s, settings: settings) { return r } else { return nil }
        }
        check("plain text is kept", kept(text("hello world")))
        check("whitespace only is not kept", skip(text("  \n ")) == .empty)
        check("concealed (password manager) content is skipped", skip(text("hunter2", types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"])) == .concealed)
        check("transient and auto-generated content is skipped",
              skip(text("x", types: ["org.nspasteboard.TransientType"])) == .concealed && skip(text("x", types: ["org.nspasteboard.AutoGeneratedType"])) == .concealed)
        check("1Password's own marker is skipped", skip(text("x", types: ["com.agilebits.onepassword"])) == .concealed)
        check("password managers are excluded by source", skip(text("x", source: "com.1password.1password")) == .excludedApp
              && skip(text("x", source: "com.bitwarden.desktop")) == .excludedApp && skip(text("x", source: "com.apple.keychainaccess")) == .excludedApp
              && skip(text("x", source: "com.apple.Passwords")) == .excludedApp)
        check("ordinary apps are not excluded", kept(text("x y", source: "com.apple.TextEdit")))
        var ex = base; ex.excludedApps = ["com.example.Secret"]
        check("the user's excluded apps are skipped (any case)", skip(text("x y", source: "com.example.secret"), ex) == .excludedApp)
        check("card number (Luhn) is skipped", skip(text("4111 1111 1111 1111")) == .secret && skip(text("4111-1111-1111-1111")) == .secret)
        check("digits that fail the check digit are kept", kept(text("4111 1111 1111 1112")))
        check("phone numbers and short numbers are kept", kept(text("+39 333 1234567")) && kept(text("12345")))
        check("API tokens are skipped", ClipRules.looksLikeSecret("ghp_aBcD1234eFgH5678iJkL9012mNoP3456qRsT")
              && ClipRules.looksLikeSecret("AKIAIOSFODNN7EXAMPLE") && ClipRules.looksLikeSecret("sk-proj-Ab12Cd34Ef56Gh78Ij90"))
        check("a JWT is skipped", ClipRules.looksLikeSecret("eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N_XgL0n3I9PlFUP0THsR8U"))
        check("a private key block is skipped", ClipRules.looksLikeSecret("-----BEGIN OPENSSH PRIVATE KEY-----\nabc\n-----END OPENSSH PRIVATE KEY-----"))
        check("a long random string is skipped", ClipRules.looksLikeSecret("q8Zr2LkT9vXw4NbP7sHd3FgJ6mYc"))
        check("URLs, paths, words, e-mails, hashes and UUIDs are kept",
              !ClipRules.looksLikeSecret("https://github.com/Mattiakart/cocaine/releases/tag/v1.7.3")
              && !ClipRules.looksLikeSecret("/Users/someone/Library/Application Support/Cocaine")
              && !ClipRules.looksLikeSecret("Supercalifragilisticexpialidocious")
              && !ClipRules.looksLikeSecret("mattia.example1234567890@example.com")
              && !ClipRules.looksLikeSecret("e23874c1f0a9b8c7d6e5f4a3b2c1d0e9f8a7b6c5")
              && !ClipRules.looksLikeSecret("123E4567-E89B-12D3-A456-426614174000")
              && !ClipRules.looksLikeSecret("brew upgrade --cask cocaine"))
        var noSecrets = base; noSecrets.skipSecrets = false
        check("with the secret filter off, a card number is kept", kept(text("4111 1111 1111 1111"), noSecrets))
        var pat = base; pat.patterns = ["^IBAN", "\\bconfidential\\b", "(unclosed"]
        check("the user's pattern skips matching text", skip(text("IBAN IT60X0542811101000000123456"), pat) == .pattern
              && skip(text("this is Confidential stuff"), pat) == .pattern)
        check("an invalid pattern is ignored, not a crash, and refused when typed", kept(text("hello there"), pat) && !ClipRules.validPattern("(unclosed")
              && ClipRules.validPattern("^IBAN") && !ClipRules.validPattern(""))
        var tiny = base; tiny.maxItemMB = 1
        check("text over the item size is skipped", skip(text(String(repeating: "a", count: 1_000_001)), tiny) == .tooBig)
        check("an image over the item size is skipped", skip(ClipSnapshot(types: ["public.png"], image: Data(count: 1_000_001), width: 1, height: 1), tiny) == .tooBig
              && skip(ClipSnapshot(types: ["public.tiff"], imageTooBig: true), tiny) == .tooBig)
        check("files win over their names as text", {
            guard case .keep(let i) = ClipRules.decide(ClipSnapshot(types: ["public.file-url", "public.utf8-plain-text"], text: "a.txt",
                                                                    files: [URL(fileURLWithPath: "/tmp/a.txt")]), settings: base) else { return false }
            return i.kind == .files && i.paths == ["/tmp/a.txt"]
        }())
        check("our own writes are not captured", skip(ClipSnapshot(types: [ClipRules.ownType], ours: true, text: "x")) == .own)

        // MARK: the list
        let t0 = Date(timeIntervalSince1970: 1_790_000_000)
        var core = ClipHistoryCore()
        let a = ClipItem.text("alpha", date: t0)
        core.add(a); core.add(.text("beta", date: t0 + 1)); core.add(.text("alpha", date: t0 + 2))
        check("dedupe: the same text again moves to the top, no duplicate", core.items.map(\.text) == ["alpha", "beta"] && core.items[0].id == a.id
              && core.items[0].date == t0 + 2)
        core.add(.text("alpha", date: t0 + 3))
        check("dedupe: copying the top item again keeps one", core.items.count == 2)
        core.add(.text("Alpha", date: t0 + 4))
        check("dedupe: different text (case) is a different item", core.items.count == 3)

        var lim = base; lim.maxItems = 3; lim.maxAgeHours = 0
        core = ClipHistoryCore()
        for i in 0..<5 { core.add(.text("n\(i)", date: t0 + Double(i))) }
        core.items[core.items.firstIndex { $0.text == "n0" }!].pinned = true
        let pruned = core.prune(now: t0 + 10, settings: lim)
        check("count limit drops the oldest, favorites survive and don't count", core.items.map(\.text) == ["n4", "n3", "n2", "n0"] && pruned.map(\.text) == ["n1"])
        var age = base; age.maxAgeHours = 24
        core = ClipHistoryCore()
        core.add(.text("old", date: t0 - 3 * 86400)); core.add(.text("oldfav", date: t0 - 3 * 86400)); core.add(.text("new", date: t0))
        core.items[core.items.firstIndex { $0.text == "oldfav" }!].pinned = true
        core.prune(now: t0, settings: age)
        check("age limit removes old items, not favorites", core.items.map(\.text).sorted() == ["new", "oldfav"])
        var space = base; space.maxTotalMB = 1; space.maxAgeHours = 0
        core = ClipHistoryCore()
        for i in 0..<4 { core.add(.image(png: Data(repeating: UInt8(i), count: 400_000), width: 10, height: 10, date: t0 + Double(i))) }
        core.prune(now: t0, settings: space)
        check("total size limit drops the oldest until it fits", core.items.count == 2 && core.items.reduce(0) { $0 + $1.bytes } <= 1_000_000)
        var noAge = base; noAge.maxAgeHours = 0
        core = ClipHistoryCore(); core.add(.text("ancient", date: t0 - 400 * 86400)); core.prune(now: t0, settings: noAge)
        check("'no limit' age keeps everything", core.items.count == 1)

        core = ClipHistoryCore()
        core.add(.text("Café au lait recipe")); core.add(.files(["/Users/x/Documents/Report Q3.pdf"]))
        core.add(.image(png: Data([1]), width: 1920, height: 1080)); core.add(.text("brew upgrade --cask cocaine"))
        core.items[core.items.firstIndex { $0.text.hasPrefix("brew") }!].pinned = true
        check("search: any case and accents", core.filtered("CAFE", favoritesOnly: false).count == 1)
        check("search: every word must match", core.filtered("cafe recipe", favoritesOnly: false).count == 1 && core.filtered("cafe brew", favoritesOnly: false).isEmpty)
        check("search: file names and folders", core.filtered("report", favoritesOnly: false).first?.kind == .files
              && core.filtered("documents", favoritesOnly: false).count == 1)
        check("search: image size", core.filtered("1920", favoritesOnly: false).first?.kind == .image)
        check("search: what describe adds (source app)", core.filtered("terminal", favoritesOnly: false, describe: { $0.text.hasPrefix("brew") ? "Terminal" : "" }).count == 1)
        check("favorites only", core.filtered("", favoritesOnly: true).map(\.text) == ["brew upgrade --cask cocaine"])
        check("empty search shows everything", core.filtered("  ", favoritesOnly: false).count == 4)

        // MARK: encryption
        let k1 = SymmetricKey(size: .bits256), k2 = SymmetricKey(size: .bits256)
        let secret = Data("the clipboard text".utf8)
        let sealed = try? ClipCrypto.seal(secret, key: k1, context: "index")
        check("encryption round trip", sealed.flatMap { try? ClipCrypto.open($0, key: k1, context: "index") } == secret)
        check("the sealed data doesn't contain the text", sealed.map { $0.range(of: secret) == nil } ?? false)
        check("a wrong key is rejected", sealed.map { (try? ClipCrypto.open($0, key: k2, context: "index")) == nil } ?? false)
        check("a changed byte is rejected", sealed.map { s -> Bool in var d = s; d[d.count - 1] ^= 1; return (try? ClipCrypto.open(d, key: k1, context: "index")) == nil } ?? false)
        check("data moved to another place (context) is rejected", sealed.map { (try? ClipCrypto.open($0, key: k1, context: "image:x")) == nil } ?? false)
        check("not our format is rejected", (try? ClipCrypto.open(Data("hello".utf8), key: k1, context: "index")) == nil)

        // MARK: the store
        func perms(_ u: URL) -> Int { ((try? fm.attributesOfItem(atPath: u.path))?[.posixPermissions] as? NSNumber)?.intValue ?? -1 }
        let keys = MemoryKeyStore()
        let dir = root.appendingPathComponent("store")
        let store = ClipStore(dir: dir, keys: keys)
        check("store: unlocking makes and keeps a 256-bit key", (try? store.unlock()) != nil && keys.key?.count == 32)
        let png = samplePNG()
        let img = ClipItem.image(png: png, width: 4, height: 3, date: t0)
        var fav = ClipItem.text("favorite text", date: t0); fav.pinned = true
        let list = [ClipItem.text("hello secret world", date: t0, source: "com.apple.TextEdit"), fav, ClipItem.files(["/tmp/x.txt"], date: t0), img]
        try? store.writeImage(img.id, png)
        let saved = (try? store.saveIndex(list)) != nil
        let back = ClipStore(dir: dir, keys: keys)
        try? back.unlock()
        let loaded = back.load()
        check("store: round trip of text, files, image, star, source", saved && loaded.problem == .none && loaded.items.count == 4
              && loaded.items[0].text == "hello secret world" && loaded.items[0].source == "com.apple.TextEdit" && loaded.items[1].pinned
              && loaded.items[2].paths == ["/tmp/x.txt"] && back.readImage(img.id) == png && loaded.items[3].payload == nil)
        check("store: folder 0700, files 0600", perms(dir) == 0o700 && perms(store.index) == 0o600 && perms(store.blob(img.id)) == 0o600)
        let indexBytes = (try? Data(contentsOf: store.index)) ?? Data()
        check("store: nothing readable on disk", indexBytes.range(of: Data("hello secret world".utf8)) == nil && indexBytes.range(of: Data("/tmp/x.txt".utf8)) == nil
              && ((try? Data(contentsOf: store.blob(img.id)))?.range(of: png.prefix(16)) == nil))
        check("store: no temp files left behind", !((try? fm.contentsOfDirectory(atPath: dir.path)) ?? []).contains { $0.hasPrefix(".tmp-") })
        let wrongKey = ClipStore(dir: dir, keys: MemoryKeyStore())
        try? wrongKey.unlock()
        let wrongLoad = wrongKey.load()
        let asides = ((try? fm.contentsOfDirectory(atPath: dir.path)) ?? []).filter { $0.hasPrefix("unreadable-") }
        let aside = asides.first.map { dir.appendingPathComponent($0) }
        check("store: another key can't read it (set aside with its images, nothing deleted; starts empty)", wrongLoad.items.isEmpty
              && wrongLoad.problem == .unreadableIndex && asides.count == 1 && !fm.fileExists(atPath: store.blob(img.id).path)
              && aside.map { fm.fileExists(atPath: $0.appendingPathComponent(store.index.lastPathComponent).path)
                             && fm.fileExists(atPath: $0.appendingPathComponent(store.blob(img.id).lastPathComponent).path) } == true)
        do {   // there, but unreadable (permissions, I/O): not "no history" (which would delete the images)
            let d3 = root.appendingPathComponent("store3"), k3 = MemoryKeyStore(), s3 = ClipStore(dir: d3, keys: k3)
            try? s3.unlock()
            let i3 = ClipItem.image(png: png, width: 4, height: 3)
            try? s3.writeImage(i3.id, png); try? s3.saveIndex([i3])
            chmod(s3.index.path, 0)
            let r3 = s3.load()
            let kept = ((try? fm.contentsOfDirectory(atPath: d3.path)) ?? []).filter { $0.hasPrefix("unreadable-") }
            check("store: an index that can't be read keeps its images (set aside, never removed as orphans)", r3.problem == .unreadableIndex
                  && kept.count == 1 && fm.fileExists(atPath: d3.appendingPathComponent(kept[0]).appendingPathComponent(s3.blob(i3.id).lastPathComponent).path))
            try? fm.removeItem(at: d3)
        }

        let dir2 = root.appendingPathComponent("store2")
        let keys2 = MemoryKeyStore()
        let s2 = ClipStore(dir: dir2, keys: keys2)
        try? s2.unlock()
        try? s2.saveIndex([.text("a")])
        try? Data("garbage, not an index".utf8).write(to: s2.index)
        let corrupt = s2.load()
        check("store: a damaged index is recovered from (empty, set aside)", corrupt.items.isEmpty && corrupt.problem == .unreadableIndex)
        // One bad item among good ones: only it is lost.
        if let key = keys2.key {
            let k = SymmetricKey(data: key)
            let good = try! JSONEncoder().encode(ClipItem.text("good one"))
            let json = "{\"v\":1,\"items\":[\(String(data: good, encoding: .utf8)!),{\"kind\":\"nonsense\"}]}"
            try? ClipCrypto.seal(Data(json.utf8), key: k, context: "index").write(to: s2.index)
            let partial = s2.load()
            check("store: a bad item is dropped, the others load", partial.items.map(\.text) == ["good one"] && partial.problem == .droppedItems(1))
            let newer = "{\"v\":2,\"items\":[]}"
            try? ClipCrypto.seal(Data(newer.utf8), key: k, context: "index").write(to: s2.index)
            check("store: a newer schema isn't misread", s2.load().problem == .unreadableIndex)
        } else { check("store: key present", false) }
        let lostImg = ClipItem.image(png: png, width: 4, height: 3)
        try? s2.saveIndex([lostImg, .text("still here")])
        let orphan = s2.blob(UUID())
        try? Data("x".utf8).write(to: orphan)
        let lost = s2.load()
        check("store: an image whose file is gone is dropped; stray files are removed", lost.items.map(\.text) == ["still here"]
              && lost.problem == .droppedItems(1) && !fm.fileExists(atPath: orphan.path))
        check("store: wipe removes the folder and the key", (try? s2.wipe()) != nil && !fm.fileExists(atPath: dir2.path) && keys2.key == nil && !s2.unlocked)

        // MARK: the history, with a fake clipboard
        func history(_ name: String, keys: MemoryKeyStore = MemoryKeyStore(), board: FakePasteboard = FakePasteboard(), d: UserDefaults? = nil) -> ClipboardHistory {
            let h = ClipboardHistory(defaults: d ?? defaults(), dir: root.appendingPathComponent(name), keys: keys, board: board)
            h.frontApp = { "com.apple.TextEdit" }
            return h
        }
        let fb = FakePasteboard()
        let h = history("h1", board: fb)
        check("history: memory only by default", !h.settings.persist && !h.saving)
        fb.put(text("first")); h.captureNow()
        fb.put(text("second")); h.captureNow()
        fb.put(text("first")); h.captureNow()
        check("history: captures and dedupes (moved to top)", h.items.map(\.text) == ["first", "second"])
        check("history: the source app is recorded", h.items[0].source == "com.apple.TextEdit")
        check("history: memory only writes nothing to disk", !fm.fileExists(atPath: root.appendingPathComponent("h1").path))
        let reads = fb.dataReads
        fb.put(text("hunter2", types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"])); h.captureNow()
        check("history: concealed content isn't kept, or even read", h.items.count == 2 && fb.dataReads == reads)
        var exS = h.settings; exS.excludedApps = ["com.example.vault"]; h.update(exS)
        h.frontApp = { "com.example.vault" }
        fb.put(text("from the vault")); h.captureNow()
        check("history: the frontmost excluded app's copy isn't kept or read", h.items.count == 2 && fb.dataReads == reads)
        h.frontApp = { "com.apple.TextEdit" }
        check("history: copying an item again isn't captured as new, and moves it up", h.copy(h.items[1]) && h.items.map(\.text) == ["second", "first"]
              && fb.written.last?.text == "second")
        h.frontApp = { "com.example.other" }
        h.captureNow()
        check("history: …even when the clipboard is read after it", h.items.count == 2 && h.items[0].source == "com.apple.TextEdit")
        h.frontApp = { "com.apple.TextEdit" }
        h.paused = true
        fb.put(text("while paused")); h.captureNow()
        h.paused = false
        h.captureNow()
        check("history: nothing copied while paused is kept, even after resuming", !h.items.contains { $0.text == "while paused" })
        fb.put(text("late")); fb.emptyReadsLeft = 1; h.captureNow()
        check("history: content that arrives late is read again", h.items.first?.text == "late")
        h.togglePin(h.items.first { $0.text == "first" }!.id)
        h.clearHistory()
        check("history: clear keeps the favorites", h.items.map(\.text) == ["first"])
        h.remove(h.items[0].id)
        check("history: delete one item", h.items.isEmpty)
        fb.put(text("from app x", source: "com.example.x")); h.captureNow()
        fb.put(text("from textedit")); h.captureNow()
        var exX = h.settings; exX.excludedApps.append("com.example.x"); h.update(exX)
        check("history: excluding an app removes what came from it", h.items.map(\.text) == ["from textedit"])
        h.query = "TEXTEDIT"
        check("history: search sees the text", h.visible.count == 1)
        h.query = "nothing like this"
        check("history: search filters", h.visible.isEmpty)
        h.query = ""

        // file references
        let realFile = root.appendingPathComponent("Real Report.pdf"), goneFile = root.appendingPathComponent("Gone.pdf")
        try? Data("pdf".utf8).write(to: realFile); try? Data("pdf".utf8).write(to: goneFile)
        fb.put(ClipSnapshot(types: ["public.file-url"], files: [realFile])); h.captureNow()
        fb.put(ClipSnapshot(types: ["public.file-url"], files: [goneFile])); h.captureNow()
        try? fm.removeItem(at: goneFile)
        h.refreshMissingNow()
        let realItem = h.items.first { $0.paths == [realFile.path] }, goneItem = h.items.first { $0.paths == [goneFile.path] }
        check("files: kept as references (paths), not copies", realItem?.kind == .files && realItem?.bytes ?? 0 < 200)
        check("files: a missing file is flagged, a present one isn't", goneItem.map { h.missing.contains($0.id) } == true && realItem.map { !h.missing.contains($0.id) } == true)
        check("files: a missing file can't be copied again; a present one can", goneItem.map { !h.copy($0) } == true && realItem.map { h.copy($0) } == true
              && fb.written.last?.paths == [realFile.path])

        // images
        fb.put(ClipSnapshot(types: ["public.png"], image: png, width: 4, height: 3)); h.captureNow()
        let imgItem = h.items.first { $0.kind == .image }
        check("images: kept with their size, copied back with their data", imgItem?.width == 4 && imgItem.map { h.imageData($0) == png } == true
              && imgItem.map { h.copy($0) } == true && fb.written.last?.kind == .image)

        // limits through the history
        var small = h.settings; small.maxItems = 2; small.maxAgeHours = 0; h.update(small)
        check("history: lowering the limit prunes at once", h.items.filter { !$0.pinned }.count == 2)
        var dated = h.settings; dated.maxAgeHours = 1; dated.maxItems = 50; h.update(dated)
        h.now = { Date().addingTimeInterval(7200) }
        h.expire()
        check("history: the age limit is applied periodically, without new copies", h.items.isEmpty)
        h.now = Date.init

        // MARK: persistence
        let pk = MemoryKeyStore(), pd = defaults(), pb = FakePasteboard()
        let ph = history("p", keys: pk, board: pb, d: pd)
        pb.put(text("before saving")); ph.captureNow()
        ph.setPersist(true)
        pb.put(text("saved text")); ph.captureNow()
        pb.put(ClipSnapshot(types: ["public.png"], image: png, width: 4, height: 3)); ph.captureNow()
        ph.togglePin(ph.items.first { $0.text == "before saving" }!.id)
        ph.flush()
        let pdir = root.appendingPathComponent("p")
        check("persistence: on, it writes encrypted files and keeps a key", ph.saving && pd.data(forKey: ClipSettings.key) != nil && pk.key != nil
              && fm.fileExists(atPath: pdir.appendingPathComponent("index.ccl").path))
        let again = history("p", keys: pk, board: FakePasteboard(), d: pd)
        again.start(); again.stop()
        let restoredImage = again.items.first { $0.kind == .image }
        check("persistence: a restart gets the history back, star and image included",
              again.items.map(\.text).filter { !$0.isEmpty } == ["saved text", "before saving"] && again.items.first { $0.text == "before saving" }?.pinned == true
              && restoredImage.map { again.imageData($0) == png } == true)
        // old items expire at load
        var aged = again.settings; aged.maxAgeHours = 1; again.update(aged); again.flush()
        let later = history("p", keys: pk, board: FakePasteboard(), d: pd)
        later.now = { Date().addingTimeInterval(3 * 3600) }
        later.start(); later.stop()
        check("persistence: expired items are dropped at load, favorites stay", later.items.map(\.text) == ["before saving"])
        later.setPersist(false, wipe: false)
        check("persistence: off and kept, the files stay (encrypted), the key too", !later.saving && fm.fileExists(atPath: pdir.path) && pk.key != nil)
        later.setPersist(true)
        later.setPersist(false, wipe: true)
        check("persistence: off and wiped, files and key are gone", !fm.fileExists(atPath: pdir.path) && pk.key == nil && !later.settings.persist)

        let fk = MemoryKeyStore(); fk.failing = true
        let fh = history("f", keys: fk)
        fh.add(.text("kept in memory"))
        fh.setPersist(true)
        check("persistence: no Keychain, no saving (memory only, said plainly)", !fh.saving && !fh.settings.persist && fh.problem != nil
              && !fm.fileExists(atPath: root.appendingPathComponent("f").path) && fh.items.count == 1)
        do {   // a Keychain that says no at launch (locked, a prompt refused) doesn't turn the choice off for good
            let lk = MemoryKeyStore(), ld = defaults()
            let lh = history("l", keys: lk, d: ld)
            lh.setPersist(true); lh.add(.text("saved")); lh.flush()
            lk.failing = true
            let locked = history("l", keys: lk, d: ld)
            locked.start(); locked.stop()
            lk.failing = false
            let next = history("l", keys: lk, d: ld)
            next.start(); next.stop()
            check("persistence: a Keychain refusal at launch keeps the choice; the next launch saves again",
                  !locked.saving && locked.problem != nil && ClipSettings.load(ld).persist && next.saving && next.items.map(\.text) == ["saved"])
        }

        let wk = MemoryKeyStore(), wb = FakePasteboard()
        let wh = history("w", keys: wk, board: wb)
        wh.setPersist(true)
        wb.put(text("one")); wh.captureNow()
        wb.put(ClipSnapshot(types: ["public.png"], image: png, width: 4, height: 3)); wh.captureNow()
        wh.togglePin(wh.items[0].id)
        wh.flush()
        let oldKey = wk.key
        let wiped = wh.deleteEverything()
        wh.flush()
        let wdir = root.appendingPathComponent("w")
        let leftovers = ((try? fm.contentsOfDirectory(atPath: wdir.path)) ?? []).filter { $0 != "index.ccl" }
        check("delete everything: items, favorites, files and key are gone", wiped && wh.items.isEmpty && leftovers.isEmpty && wk.key != oldKey)
        let afterWipe = history("w", keys: wk, board: FakePasteboard())
        afterWipe.setPersist(true)
        check("delete everything: nothing comes back after a restart", afterWipe.items.isEmpty)
        afterWipe.setPersist(false, wipe: true)
        let lh = history("leftover", keys: MemoryKeyStore())
        lh.setPersist(true); lh.add(.text("x")); lh.flush(); lh.setPersist(false, wipe: false)
        lh.deleteEverything()
        check("delete everything: also removes files kept from an earlier time", !fm.fileExists(atPath: root.appendingPathComponent("leftover").path))

        var oldSettings = Data("{\"maxItems\":200}".utf8)
        let sd = defaults(); sd.set(oldSettings, forKey: ClipSettings.key)
        check("settings: missing keys take defaults", ClipSettings.load(sd).maxItems == 200 && !ClipSettings.load(sd).persist && ClipSettings.load(sd).skipSecrets)
        oldSettings = Data("garbage".utf8); sd.set(oldSettings, forKey: ClipSettings.key)
        check("settings: damaged settings fall back to defaults", ClipSettings.load(sd) == ClipSettings())

        failed += realPasteboard()
        failed += realKeychain(root)
        return failed
    }

    /// A 4×3 PNG.
    static func samplePNG() -> Data {
        let rep = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 4, pixelsHigh: 3, bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
                                   isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)!
        rep.setColor(NSColor(deviceRed: 1, green: 0.4, blue: 0.7, alpha: 1), atX: 1, y: 1)
        return rep.representation(using: .png, properties: [:])!
    }

    /// The real NSPasteboard code, on a uniquely named pasteboard (never the general one).
    private static func realPasteboard() -> Int {
        var failed = 0
        func check(_ name: String, _ ok: Bool) { print((ok ? "PASS" : "FAIL") + "  clipboard: " + name); if !ok { failed += 1 } }
        let pb = NSPasteboard(name: NSPasteboard.Name("local.cocaine.cliptest.\(getpid()).\(UUID().uuidString)"))
        defer { pb.releaseGlobally() }
        let board = SystemPasteboard(pb)
        let all: ([String], String?) -> Bool = { _, _ in true }
        pb.clearContents(); pb.setString("plain words", forType: .string)
        check("pasteboard: plain text is read", board.snapshot(maxImageBytes: 1_000_000, allowed: all).text == "plain words")
        pb.clearContents()
        let rtf = NSAttributedString(string: "bold words", attributes: [.font: NSFont.boldSystemFont(ofSize: 12)])
        pb.setData(try? rtf.data(from: NSRange(location: 0, length: rtf.length), documentAttributes: [.documentType: NSAttributedString.DocumentType.rtf]), forType: .rtf)
        check("pasteboard: rich text keeps its plain text", board.snapshot(maxImageBytes: 1_000_000, allowed: all).text == "bold words")
        pb.clearContents()
        pb.setString("hunter2", forType: .string); pb.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        let concealed = board.snapshot(maxImageBytes: 1_000_000) { types, _ in !ClipRules.isConcealed(types) }
        check("pasteboard: concealed content isn't read", concealed.text == nil && ClipRules.isConcealed(concealed.types))
        pb.clearContents()
        pb.setString("x", forType: .string); pb.setString("com.example.app", forType: NSPasteboard.PasteboardType("org.nspasteboard.source"))
        check("pasteboard: the source app marker is read", board.snapshot(maxImageBytes: 1_000_000, allowed: all).source == "com.example.app")
        let png = samplePNG()
        pb.clearContents(); pb.setData(png, forType: .png)
        let im = board.snapshot(maxImageBytes: 1_000_000, allowed: all)
        check("pasteboard: a PNG is read with its size", im.image == png && im.width == 4 && im.height == 3)
        pb.clearContents(); pb.setData(NSBitmapImageRep(data: png)!.tiffRepresentation!, forType: .tiff)
        let tf = board.snapshot(maxImageBytes: 1_000_000, allowed: all)
        check("pasteboard: a TIFF becomes a PNG", tf.image.map { NSBitmapImageRep(data: $0) != nil && $0.starts(with: [0x89, 0x50, 0x4E, 0x47]) } == true && tf.width == 4)
        check("pasteboard: an image over the limit isn't kept", board.snapshot(maxImageBytes: 10, allowed: all).imageTooBig)
        let file = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("cocaine-clip-\(getpid()).txt")
        try? Data("x".utf8).write(to: file)
        defer { try? FileManager.default.removeItem(at: file) }
        pb.clearContents(); pb.writeObjects([file as NSURL])
        check("pasteboard: copied files are read as references", board.snapshot(maxImageBytes: 1_000_000, allowed: all).files.map(\.path) == [file.path])
        // Writing back: the right types, and marked as ours.
        let before = pb.changeCount
        let c1 = board.write(.text("again"), payload: nil)
        let back = board.snapshot(maxImageBytes: 1_000_000, allowed: all)
        check("pasteboard: text written back is plain text, marked as ours", c1 != nil && c1 != before && pb.string(forType: .string) == "again" && back.ours)
        _ = board.write(.image(png: png, width: 4, height: 3), payload: png)
        check("pasteboard: an image is written back as PNG and TIFF", pb.data(forType: .png) == png && pb.data(forType: .tiff) != nil
              && NSImage(pasteboard: pb) != nil)
        _ = board.write(.files([file.path]), payload: nil)
        let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL]
        check("pasteboard: files are written back as file URLs", urls?.map(\.path) == [file.path] && pb.types?.contains(NSPasteboard.PasteboardType(ClipRules.ownType)) == true)
        check("pasteboard: a missing file isn't written", board.write(.files(["/nonexistent/cocaine-\(UUID().uuidString)"]), payload: nil) == nil)
        return failed
    }

    /// The Keychain code against a temporary keychain file (not the login keychain), made and deleted here.
    private static func realKeychain(_ root: URL) -> Int {
        var failed = 0
        func check(_ name: String, _ ok: Bool) { print((ok ? "PASS" : "FAIL") + "  clipboard: " + name); if !ok { failed += 1 } }
        let path = root.appendingPathComponent("test.keychain-db").path
        func security(_ args: [String]) -> Int32 {
            let p = Process()
            p.executableURL = URL(fileURLWithPath: "/usr/bin/security")
            p.arguments = args
            p.standardOutput = FileHandle.nullDevice; p.standardError = FileHandle.nullDevice
            do { try p.run() } catch { return -1 }
            p.waitUntilExit()
            return p.terminationStatus
        }
        guard security(["create-keychain", "-p", "cocaine-test", path]) == 0 else {
            print("SKIP  clipboard: keychain (can't make a temporary keychain here)")
            return 0
        }
        defer { _ = security(["delete-keychain", path]) }
        _ = security(["unlock-keychain", "-p", "cocaine-test", path])
        var kc: SecKeychain?
        guard SecKeychainOpen(path, &kc) == errSecSuccess, let kc else { check("keychain: temporary keychain opens", false); return failed }
        let store = KeychainKeyStore(service: "local.cocaine.clipboard.test", account: "k", keychain: kc)
        check("keychain: nothing there at first", (try? store.load()) == .some(nil))
        let key = Data((0..<32).map { _ in UInt8.random(in: 0...255) })
        check("keychain: a key is saved and read back", (try? store.save(key)) != nil && (try? store.load()) == .some(key))
        let other = Data((0..<32).map { _ in UInt8.random(in: 0...255) })
        check("keychain: saving again replaces it", (try? store.save(other)) != nil && (try? store.load()) == .some(other))
        let cs = ClipStore(dir: root.appendingPathComponent("kc"), keys: store)
        check("keychain: the store uses it", (try? cs.unlock()) != nil && (try? cs.saveIndex([.text("k")])) != nil)
        check("keychain: delete removes it (and deleting again is fine)", (try? store.delete()) != nil && (try? store.load()) == .some(nil) && (try? store.delete()) != nil)
        check("keychain: the login keychain was not used", (try? KeychainKeyStore(service: "local.cocaine.clipboard.test", account: "k").load()) == .some(nil))
        return failed
    }
}
